"""The default of each setting, in one place. `CaseStore` and the API's `Settings` both read them, so they cannot drift.

What each setting means is written beside it in `northstar_api.settings`.
"""

ACCESS_TOKEN_MINUTES = 15
REQUEST_LIMIT = 60
DAILY_TOKEN_BUDGET = 20_000
CHAT_TURNS_PER_CUSTOMER = 10
CHAT_TURNS_PER_DAY = 500
TURN_DEADLINE_SECONDS = 45
FAILED_TURNS_BEFORE_FOLLOW_UP = 3
LIVE_CHAT_ENABLED = False
LIVE_CHATS_PER_SPECIALIST = 2
OFFER_ACCEPT_SECONDS = 45
OFFERS_BEFORE_LEAVE_MESSAGE = 3
MISSED_OFFERS_BEFORE_AWAY = 2
DESK_CHECK_IN_SECONDS = 60
LINE_GONE_MINUTES = 2
LONGEST_WAIT_MINUTES = 20
WAIT_HISTORY_DAYS = 7
WAIT_HISTORY_CHATS = 5
QUIET_NUDGE_MINUTES = 2
QUIET_IDLE_MINUTES = 3
QUIET_CLOSE_MINUTES = 15
QUIET_SPECIALIST_MINUTES = 2
